# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Tue Apr 08 00:54:27 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(792, 565)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btnLoadImage = QtGui.QPushButton(self.groupBox)
        self.btnLoadImage.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.btnLoadImage.setObjectName(_fromUtf8("btnLoadImage"))
        self.txtFileName = QtGui.QLineEdit(self.groupBox)
        self.txtFileName.setGeometry(QtCore.QRect(10, 20, 171, 20))
        self.txtFileName.setObjectName(_fromUtf8("txtFileName"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 271, 141))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.txtSEFG = QtGui.QLineEdit(self.groupBox_3)
        self.txtSEFG.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.txtSEFG.setObjectName(_fromUtf8("txtSEFG"))
        self.btnSEFG = QtGui.QPushButton(self.groupBox_3)
        self.btnSEFG.setGeometry(QtCore.QRect(220, 20, 21, 23))
        self.btnSEFG.setObjectName(_fromUtf8("btnSEFG"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 80, 251, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.txtSEBG = QtGui.QLineEdit(self.groupBox_4)
        self.txtSEBG.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.txtSEBG.setObjectName(_fromUtf8("txtSEBG"))
        self.btnSEBG = QtGui.QPushButton(self.groupBox_4)
        self.btnSEBG.setGeometry(QtCore.QRect(220, 20, 21, 23))
        self.btnSEBG.setObjectName(_fromUtf8("btnSEBG"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(290, 10, 491, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabImage = QtGui.QWidget()
        self.tabImage.setObjectName(_fromUtf8("tabImage"))
        self.lblImage = QtGui.QLabel(self.tabImage)
        self.lblImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblImage.setText(_fromUtf8(""))
        self.lblImage.setObjectName(_fromUtf8("lblImage"))
        self.tabWidget.addTab(self.tabImage, _fromUtf8(""))
        self.tabSEFG = QtGui.QWidget()
        self.tabSEFG.setObjectName(_fromUtf8("tabSEFG"))
        self.lblSEFGImage = QtGui.QLabel(self.tabSEFG)
        self.lblSEFGImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSEFGImage.sizePolicy().hasHeightForWidth())
        self.lblSEFGImage.setSizePolicy(sizePolicy)
        self.lblSEFGImage.setText(_fromUtf8(""))
        self.lblSEFGImage.setObjectName(_fromUtf8("lblSEFGImage"))
        self.tabWidget.addTab(self.tabSEFG, _fromUtf8(""))
        self.tabSEBG = QtGui.QWidget()
        self.tabSEBG.setObjectName(_fromUtf8("tabSEBG"))
        self.lblSEBGImage = QtGui.QLabel(self.tabSEBG)
        self.lblSEBGImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblSEBGImage.setText(_fromUtf8(""))
        self.lblSEBGImage.setObjectName(_fromUtf8("lblSEBGImage"))
        self.tabWidget.addTab(self.tabSEBG, _fromUtf8(""))
        self.tabKSHMT = QtGui.QWidget()
        self.tabKSHMT.setObjectName(_fromUtf8("tabKSHMT"))
        self.lblKSHMTImage = QtGui.QLabel(self.tabKSHMT)
        self.lblKSHMTImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblKSHMTImage.setText(_fromUtf8(""))
        self.lblKSHMTImage.setObjectName(_fromUtf8("lblKSHMTImage"))
        self.tabWidget.addTab(self.tabKSHMT, _fromUtf8(""))
        self.tabSUHMT = QtGui.QWidget()
        self.tabSUHMT.setObjectName(_fromUtf8("tabSUHMT"))
        self.lblSUHMTImage = QtGui.QLabel(self.tabSUHMT)
        self.lblSUHMTImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblSUHMTImage.setText(_fromUtf8(""))
        self.lblSUHMTImage.setObjectName(_fromUtf8("lblSUHMTImage"))
        self.tabWidget.addTab(self.tabSUHMT, _fromUtf8(""))
        self.tabBAHMT = QtGui.QWidget()
        self.tabBAHMT.setObjectName(_fromUtf8("tabBAHMT"))
        self.lblBAHMTImage = QtGui.QLabel(self.tabBAHMT)
        self.lblBAHMTImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblBAHMTImage.setText(_fromUtf8(""))
        self.lblBAHMTImage.setObjectName(_fromUtf8("lblBAHMTImage"))
        self.tabWidget.addTab(self.tabBAHMT, _fromUtf8(""))
        self.tabROHMT = QtGui.QWidget()
        self.tabROHMT.setObjectName(_fromUtf8("tabROHMT"))
        self.lblROHMTImage = QtGui.QLabel(self.tabROHMT)
        self.lblROHMTImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        self.lblROHMTImage.setText(_fromUtf8(""))
        self.lblROHMTImage.setObjectName(_fromUtf8("lblROHMTImage"))
        self.tabWidget.addTab(self.tabROHMT, _fromUtf8(""))
        self.tabRGHMT = QtGui.QWidget()
        self.tabRGHMT.setObjectName(_fromUtf8("tabRGHMT"))
        self.lblRGHMTImage = QtGui.QLabel(self.tabRGHMT)
        self.lblRGHMTImage.setGeometry(QtCore.QRect(0, 0, 481, 511))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRGHMTImage.sizePolicy().hasHeightForWidth())
        self.lblRGHMTImage.setSizePolicy(sizePolicy)
        self.lblRGHMTImage.setText(_fromUtf8(""))
        self.lblRGHMTImage.setObjectName(_fromUtf8("lblRGHMTImage"))
        self.tabWidget.addTab(self.tabRGHMT, _fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 210, 271, 151))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.btnKSHMT = QtGui.QPushButton(self.groupBox_5)
        self.btnKSHMT.setGeometry(QtCore.QRect(10, 20, 251, 23))
        self.btnKSHMT.setObjectName(_fromUtf8("btnKSHMT"))
        self.btnSUHMT = QtGui.QPushButton(self.groupBox_5)
        self.btnSUHMT.setGeometry(QtCore.QRect(10, 40, 251, 23))
        self.btnSUHMT.setObjectName(_fromUtf8("btnSUHMT"))
        self.btnBAHMT = QtGui.QPushButton(self.groupBox_5)
        self.btnBAHMT.setGeometry(QtCore.QRect(10, 60, 251, 23))
        self.btnBAHMT.setObjectName(_fromUtf8("btnBAHMT"))
        self.btnROHMT = QtGui.QPushButton(self.groupBox_5)
        self.btnROHMT.setGeometry(QtCore.QRect(10, 80, 251, 23))
        self.btnROHMT.setObjectName(_fromUtf8("btnROHMT"))
        self.btnRGHMT = QtGui.QPushButton(self.groupBox_5)
        self.btnRGHMT.setGeometry(QtCore.QRect(10, 100, 251, 23))
        self.btnRGHMT.setObjectName(_fromUtf8("btnRGHMT"))
        self.btnAll = QtGui.QPushButton(self.groupBox_5)
        self.btnAll.setGeometry(QtCore.QRect(10, 120, 251, 23))
        self.btnAll.setObjectName(_fromUtf8("btnAll"))
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HMT GUI", None))
        self.groupBox.setTitle(_translate("MainWindow", "Image", None))
        self.btnLoadImage.setText(_translate("MainWindow", "load", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "SEs", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "FG", None))
        self.btnSEFG.setText(_translate("MainWindow", "ok", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "BG", None))
        self.btnSEBG.setText(_translate("MainWindow", "ok", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("MainWindow", "Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSEFG), _translate("MainWindow", "SE FG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSEBG), _translate("MainWindow", "SE BG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKSHMT), _translate("MainWindow", "KSHMT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSUHMT), _translate("MainWindow", "SUHMT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBAHMT), _translate("MainWindow", "BAHMT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabROHMT), _translate("MainWindow", "ROHMT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRGHMT), _translate("MainWindow", "RGHMT", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "HMTs", None))
        self.btnKSHMT.setText(_translate("MainWindow", "ksHMT", None))
        self.btnSUHMT.setText(_translate("MainWindow", "suHMT", None))
        self.btnBAHMT.setText(_translate("MainWindow", "baHMT", None))
        self.btnROHMT.setText(_translate("MainWindow", "roHMT", None))
        self.btnRGHMT.setText(_translate("MainWindow", "rgHMT", None))
        self.btnAll.setText(_translate("MainWindow", "all", None))

